apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bunny-saves-pvc
  namespace: bunny-game
  labels:
    app: bunny-backend
    component: storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
