apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-context
  namespace: bunny-game
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
