apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-frontend
  namespace: bunny-game
spec:
  backoffLimit: 0
  template:
    spec:
      nodeSelector:
        topology.kubernetes.io/esxi: esxi2
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - "--context=dir:///context"
        - "--dockerfile=/context/Dockerfile.frontend"
        - "--destination=172.20.10.120:5000/bunny-family-frontend:latest"
        - "--insecure"
        - "--skip-tls-verify"
        volumeMounts:
        - name: context
          mountPath: /context
      restartPolicy: Never
      volumes:
      - name: context
        persistentVolumeClaim:
          claimName: build-context
